// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHlPogEfSaoE7KQ7kgxCoo4rjydTqhV7E',
    appId: '1:486278364700:web:b9afd19910a8d1789869d9',
    messagingSenderId: '486278364700',
    projectId: 'fir-chat-6392f',
    authDomain: 'fir-chat-6392f.firebaseapp.com',
    storageBucket: 'fir-chat-6392f.firebasestorage.app',
    measurementId: 'G-7S33P6QG93',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6qYLStuWmIDDohD8wPWPVhcbQsTEfwFw',
    appId: '1:486278364700:android:c50e0ea00a4642a29869d9',
    messagingSenderId: '486278364700',
    projectId: 'fir-chat-6392f',
    storageBucket: 'fir-chat-6392f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw3WWiMn7unuE_fIxWIxq4pvbpcA7SOE0',
    appId: '1:486278364700:ios:cd158f6c6cabac789869d9',
    messagingSenderId: '486278364700',
    projectId: 'fir-chat-6392f',
    storageBucket: 'fir-chat-6392f.firebasestorage.app',
    iosBundleId: 'com.example.chatapplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw3WWiMn7unuE_fIxWIxq4pvbpcA7SOE0',
    appId: '1:486278364700:ios:cd158f6c6cabac789869d9',
    messagingSenderId: '486278364700',
    projectId: 'fir-chat-6392f',
    storageBucket: 'fir-chat-6392f.firebasestorage.app',
    iosBundleId: 'com.example.chatapplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHlPogEfSaoE7KQ7kgxCoo4rjydTqhV7E',
    appId: '1:486278364700:web:999c8b3f1f4fa69b9869d9',
    messagingSenderId: '486278364700',
    projectId: 'fir-chat-6392f',
    authDomain: 'fir-chat-6392f.firebaseapp.com',
    storageBucket: 'fir-chat-6392f.firebasestorage.app',
    measurementId: 'G-2B60Q6J2CL',
  );
}
